# Generated by Django 5.0.6 on 2024-12-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donar',
            name='profile',
        ),
        migrations.AddField(
            model_name='donar',
            name='Username',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
