# Generated by Django 5.0.6 on 2024-12-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_donar_profile_donar_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donar',
            old_name='Username',
            new_name='username',
        ),
    ]
