# Generated by Django 5.0.6 on 2024-12-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_username_donar_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donar',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
    ]
